[tool.poetry]
name = "language-processing-100-knocks"
version = "0.1.0"
description = ""
authors = ["s4na <appletea.umauma@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
